# ----------------------------------------
# GENERAL NOTES
# ----------------------------------------
# IMPORTANT:
# Make sure your AWS credentials are already configured.
# You can set them up by running 'aws configure' via the AWS CLI.

# WARNING:
# This file is just an example of how to set up the cluster.

# ----------------------------------------
# AUTHENTICATION
# ----------------------------------------

# Path to the SSH private key file used to access the instances.
key.file.path = /home/bernardo/.ssh/servers.pem
key.file.name = servers.pem

# ----------------------------------------
# GROUP DESCRIPTION
# ----------------------------------------

# Name and description of the group for identification purposes.
group.name = GRUPO-TESTE
group.desc = Um grupo de teste

# ----------------------------------------
# CLUSTER INSTANCE CONFIGURATION
# ----------------------------------------

# VPC and network-related settings.
vpc.id = vpc-0dce460fb07ee5430
subnet.id = subnet-0bfa299b4a355fa1c
securitygroup.id= sg-03fe52495ee58cce3

# Default settings for EC2 instances.
default.region = eu-central-1
default.os = ami-03250b0e01c28d196
default.instanceType = t2.micro