# ----------------------------------------
# CLUSTER SETTINGS
# ----------------------------------------
# Name of the cluster.
cluster.name = XYZ
# Number of instances in the cluster.
cluster.size = 4

